Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: datasets in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (2.12.0)
Requirement already satisfied: numpy>=1.17 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from datasets) (1.22.4)
Requirement already satisfied: pyarrow>=8.0.0 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from datasets) (11.0.0)
Requirement already satisfied: dill<0.3.7,>=0.3.0 in /u/eergun/.local/lib/python3.9/site-packages (from datasets) (0.3.6)
Requirement already satisfied: pandas in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from datasets) (2.0.3)
Requirement already satisfied: requests>=2.19.0 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from datasets) (2.31.0)
Requirement already satisfied: tqdm>=4.62.1 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from datasets) (4.65.0)
Requirement already satisfied: xxhash in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from datasets) (2.0.2)
Requirement already satisfied: multiprocess in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from datasets) (0.70.14)
Requirement already satisfied: fsspec[http]>=2021.11.1 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from datasets) (2022.5.0)
Requirement already satisfied: aiohttp in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from datasets) (3.8.5)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.11.0 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from datasets) (0.15.1)
Requirement already satisfied: packaging in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from datasets) (23.1)
Requirement already satisfied: responses<0.19 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from datasets) (0.13.3)
Requirement already satisfied: pyyaml>=5.1 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from datasets) (5.4.1)
Requirement already satisfied: filelock in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from huggingface-hub<1.0.0,>=0.11.0->datasets) (3.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from huggingface-hub<1.0.0,>=0.11.0->datasets) (4.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from requests>=2.19.0->datasets) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from requests>=2.19.0->datasets) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from requests>=2.19.0->datasets) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from requests>=2.19.0->datasets) (2023.7.22)
Requirement already satisfied: six in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from responses<0.19->datasets) (1.16.0)
Requirement already satisfied: attrs>=17.3.0 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from aiohttp->datasets) (22.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from aiohttp->datasets) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from aiohttp->datasets) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from aiohttp->datasets) (1.8.1)
Requirement already satisfied: frozenlist>=1.1.1 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from aiohttp->datasets) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from aiohttp->datasets) (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from pandas->datasets) (2022.7)
Requirement already satisfied: tzdata>=2022.1 in /sw/external/python/anaconda3_cpu/lib/python3.9/site-packages (from pandas->datasets) (2023.3)
Downloading and preparing dataset None/wikitext-103-raw-v1 to /scratch/bcyi/eergun/.cache/huggingface/datasets/parquet/wikitext-103-raw-v1-7bb180478b704b56/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec...
